### ISSUE TITLE
Unable to strip the following libraries, packaging them as they are: libNativeManchesterWrapper.so, libiconv.so, libzbar.so.

### ISSUE THREAD

**Issue by jayjupdhig** [sumup/sumup-android-sdk#140]
Hi there!

I get that warning in Android Studio. Does somebody know why?

If you need more informations, so please don't hesitate to ask me. Thanks.

With kind regards,
Jan

**Comment by jayjupdhig** [comment]
no answer??

**Comment by jayjupdhig** [comment]
???

**Comment by jayjupdhig** [comment]
Is that message a problem or harlmess?

A short "yes" or "no" is enough so i think.

Thank you for your understanding regarding my concern.


With kind regards from Switzerland,
Jan

**Comment by jayjupdhig** [comment]
???

**Comment by jayjupdhig** [comment]
No anwser?!?

**Comment by jayjupdhig** [comment]
...

**Comment by hkahl** [comment]
I got the same Warning after I switched from the deprecated "ndk.dir" in local.properties to "android.ndkPath" in build.gradle.

Yes, this is a Problem. Libs will not be stripped.

I launched gradle with debug output and noticed that gradle could not find the strip executable because the path to the NDK was not specified using "ndk.dir" property. It did not consider android.ndkPath.

This might be the source of the problem: findNdkLocation()
https://android.googlesource.com/platform/tools/base/+/refs/heads/master/build-system/gradle-core/src/main/groovy/com/android/build/gradle/internal/SdkHandler.java

Setting ndk.dir in local.properties was a workaround for me. The strip tool is found again, but there is a warning that this property is deprecated.

**Comment by jayjupdhig** [comment]
Thank you for your feedback.

"Yes, this is a Problem. Libs will not be stripped."

But it's interesting that my application works - don't no why. (???)

**Comment by hkahl** [comment]
It will work, but the libs will contain some debugging information.
The down side of this is that the lib will be unnecessarily big and it will be easier for other people to reverse engineer the libs.

**Comment by jayjupdhig** [comment]
OK, thank you for your information.

Then, so i think at least, it's the time that somebody of the SumUp company will give us an anwser about that issue.

But so it seems, they are not interested for that... (?)

**Comment by jayjupdhig** [comment]
Answer from SumUp is still pendent...

**Comment by jayjupdhig** [comment]
Still no anwser...(???)

**Comment by jayjupdhig** [comment]
Bye-bye SumUp. Now we go to Payrexx!! :-)

**Comment by leonidlewis** [comment]
Same warning here.
```
> Task :app:stripDebugDebugSymbols
Unable to strip the following libraries, packaging them as 
they are: libbetter.so, libc++_shared.so, libevent-2.1.so, 
```
This is a simple app that only shows Hello world.
But when I build the app by using `./gradlew assembleRelease` I got the above warning.
After that, when I start running the app on my emulator, I always got this warning.
How can I do?

**Comment by aenonGit** [comment]
It is likely you do not have installed the default ndk version. Each AGP has a default ndk configured, if it does not find it or if you do not specify a specific one it will show those errors: https://developer.android.com/studio/projects/install-ndk#apply-specific-version

**Comment by sharuk2k3** [comment]
![Screenshot (100)](https://user-images.githubusercontent.com/68993083/205477754-7fdd6c3e-5606-4209-9b98-d1ea21d87fc3.png)

![Screenshot (101)](https://user-images.githubusercontent.com/68993083/205477819-5d9dd851-566a-40bc-bb9c-1b0123191603.png)

Can anyone help me to solve this issue
