### ISSUE TITLE
Links to docs.sumup.com in README.md are broken

### ISSUE THREAD

**Issue by christxph** [sumup/sumup-android-sdk#93]
All links in the README.md file that link to a site under the `docs.sumup.com` domain are broken, because they redirect to https://developer.sumup.com/

**Expected**
Clicking on the "Receipts" link (http://docs.sumup.com/rest-api/transactions-api/#receipts) opens the receipts documentation.

**Actual**
The browser is redirected to https://developer.sumup.com.

**Comment by refeele** [comment]
Actually I'm very frustrated because the documentation doesn't have all the information that I need to run a good integration of the sdk. At least not in the readme file 🥺 and it lacks of a function to connect to certain card reader based on it's serial number too that will be VERY useful for mid to large deployments.

**Comment by christxph** [comment]
Looks like this was fixed in 7e015b4, closing this issue.
